[package]
name = "casper-node-launcher"
version = "0.1.0"
authors = ["Fraser Hutchison <fraser@casperlabs.io>"]
edition = "2018"
description = "A binary which runs and upgrades the casper-node of the Casper network"
readme = "README.md"
documentation = "https://docs.rs/casper-node-launcher"
homepage = "https://casperlabs.io"
repository = "https://github.com/CasperLabs/casper-node/tree/master/client"
license-file = "../LICENSE"

[dependencies]
anyhow = "1.0.38"
clap = "3.0.0-beta.2"
serde = { version = "1.0.120", features = ["derive"] }
toml = "0.5.8"
tracing = "0.1.22"
tracing-subscriber = { version = "0.2.15", features = ["json"] }

[dev-dependencies]
once_cell = "1.5.2"
tempfile = "3.2.0"
